### ISSUE TITLE
Textures dont change

### ISSUE THREAD

**Issue by sebastianxce** [aeroson/UnityProceduralPlanets#3]
Ive been learning alot from this but when I try to change the planets texture it doesnt change, also when I want more than one planet I cant seem to get worldpos to let me have more than one planet in the scene

**Comment by oznogon** [comment]
WorldPos is public, so you can set it through a script you wrote and add to the planet object.

Since there are no special getter or setter functions, you could also simply convert it to a normal public variable and set the WorldPos sector in the inspector.

**Comment by sebastianxce** [comment]
thank you! I figured out most of the issues i been having but my biggest problem is getting trees and prefabs to spawn around the planet, i have done research and dug deep and the best theorys are to use Raycast and/or Noise methods to make it look realistic, though i am new to this i have been doing research to try and understand where to code but I have came up with this, but it is very noneffective, only spawns prefabs near the surface but not facing correctly or even on the right spots... 

`  float randomX = UnityEngine.Random.Range(mesh.bounds.min.x, mesh.bounds.max.x);
     float randomZ = UnityEngine.Random.Range(mesh.bounds.min.z, mesh.bounds.max.z);
 RaycastHit hit;
 if (Physics.Raycast(new Vector3(randomX, mesh.bounds.max.y, randomZ), Vector3.down, out hit)) {
     // the raycast hit, the point on the terrain is hit.point, spawn a tree there
	planet.SendMessage("spawn", hit.point);
 }`
